"""add email verification and password reset fields to user

Revision ID: 08077a2e5f8b
Revises: 4d141e38ff6f
Create Date: 2025-06-23 11:57:05.768231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08077a2e5f8b'
down_revision: Union[str, Sequence[str], None] = '4d141e38ff6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
