"""Add indexes for frequently queried fields

Revision ID: 8efef424c52e
Revises: 12d3c97a2ff1
Create Date: 2025-07-25 18:47:53.570620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efef424c52e'
down_revision: Union[str, Sequence[str], None] = '12d3c97a2ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
